FROM juntossomosmais/dotnet-sonar:3.1

WORKDIR /app

# Restores (downloads) all NuGet packages from all projects of the solution on a separate layer
COPY ./Rabbitcs/Rabbitcs.csproj ./Rabbitcs/
COPY ./Tests/Tests.csproj ./Tests/

RUN dotnet restore ./Rabbitcs/Rabbitcs.csproj
RUN dotnet restore ./Tests/Tests.csproj

# Copy all files
COPY . ./